source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'shotgun'
gem 'pry'
gem 'minitest'
gem 'simplecov'
gem 'capybara'
gem 'launchy'
gem 'sequel'
gem 'pg'
# gem 'cane'
# gem 'reek'
# gem 'rake'
